apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-{{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-{{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: hw-{{ .Release.Namespace }}
    spec:
      containers:
      - name: hw-{{ .Release.Namespace }}
        image: us-west3-docker.pkg.dev/ageless-math-433804-h9/hybridocr/hybridocr_website:{{ .Release.Namespace }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
        env:
        - name: HYBRIDOCR_CONFIG_FILE
          value: "/secret/config.json"
        volumeMounts:
        - name: config-volume
          mountPath: /secret/config.json
          subPath: config.json
          readOnly: true
      volumes:
      - name: config-volume
        secret:
          secretName: config
