apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw-{{ .Release.Namespace }}
spec:
  ingressClassName: traefik
  rules:
  - host: {{ required "domain value is required" .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hw-{{ .Release.Namespace }}
            port:
              number: 80
