apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hybridocr-website-ingress
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - "hybridocr.com"
    - "*.hybridocr.com"
    secretName: hybridocr-tls
  rules:
  - host: {{ required "domain value is required" .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hybridocr-website-service
            port:
              number: 80
