apiVersion: v1
kind: Service
metadata:
  name: hw-{{ .Release.Namespace }}-service
  labels:
    app: hw-{{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: hw-{{ .Release.Namespace }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
