apiVersion: v1
kind: Service
metadata:
  name: hybridocr-website-service
  labels:
    app: hybridocr-website
spec:
  type: ClusterIP
  selector:
    app: hybridocr-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
