# kubectl -n ingress create secret tls hybridocr-tls --key=hybridocr.key --cert=hybridocr.crt
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
spec:
  defaultCertificate:
    secretName: hybridocr-tls
