global:
  enabled: true
  tlsDisable: true
injector:
  enabled: false
server:
  ingress:
    enabled: true
    labels: {}
    ingressClassName: "traefik"
    activeService: true
    hosts:
      - host: "vault.hybridocr.com"
        pathType: Prefix
        paths:
         - "/"
  resources:
    requests:
      cpu: "500m"
      memory: "100Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  readinessProbe:
    enabled: true
    port: 8200
    failureThreshold: 2
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
  service:
    enabled: true
    port: 8200
    targetPort: 8200
  dataStorage:
    enabled: false
  ha:
    enabled: true
    replicas: 1
    apiAddr: "https://vault.hybridocr.com"
    clusterAddr:  ## let helm fill it in
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      
      storage "gcs" {
        bucket     = "hybridocr-vault-2c7ccab9"
        ha_enabled = "true"
      }

      service_registration "kubernetes" {}

      seal "gcpckms" {
         project     = "ageless-math-433804-h9"
         region      = "us-central1"
         key_ring    = "vault-helm-unseal-kr"
         crypto_key  = "vault-helm-unseal-key"
      }
  serviceAccount:
    create: false
    name: "vault-ksa"
ui:
  enabled: true
  publishNotReadyAddresses: true
  activeVaultPodOnly: false
  serviceType: "ClusterIP"
  serviceNodePort: null
  externalPort: 8200
  targetPort: 8200
