## RUSTFLAGS="-C target-feature=+simd128" wasm-pack build --release --target web
[package]
name = "hybridocr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2" }
argon2 = "0.5.3"
nalgebra = "0.33.2"
image = { version = "0.25.5", features = ["avif-native"] }

[dev-dependencies]
imageproc = "0.25.0"
hex = "0.4.3"

[build-dependencies]
wasm-pack = "0.13.1"

[profile.release]
opt-level = 3
debug = 2
