FROM python:3.11.7-slim

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

RUN apt-get update
RUN apt-get install -y dumb-init
RUN apt-get install -y procps curl

RUN useradd -m docker
RUN chown -R docker:docker /app
USER docker
RUN pip install gunicorn
COPY website/requirements.txt /app
RUN pip install -r /app/requirements.txt
COPY website/ /app/website

ENTRYPOINT ["dumb-init"]
CMD ["/home/docker/.local/bin/uvicorn", "website.server:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers", "--forwarded-allow-ips", "*"]
